### PR TITLE
Third Milestone

### PR DESCRIPTION
**Pull request by srizzuto**
This is Milestone 3 of the project Using Bootstrap. In this part, we'll add the lasting sections at the bottom of the website with his corresponding responsiveness and style.

After completing the project will be finished.

### CODE REVIEW

**Review by henatan99 — CHANGES_REQUESTED** [review]
## Changes required :recycle:

Hi there, You have done great so far :muscle: yet you have some changes to make before your project gets approved. 

### Reminder: Please be aware that this is your first review and you will have a maximum of two more reviews left. If your project doesn't get approved at the third review, you will repeat the project again. Make sure you have made all the requested changes before you submit for re-review. 

## To highlight 
- Many features(views) of the page are as good as the original page. :+1: 

## To Improve [MANATORY]
- In the mobile view the IN THE MAGAZINE section disappears on your page
- Each image in the main magazine section (US, WORLD, ...) should have a link (a-tag) 
- Each title in the main magazine section (US, WORLD, BUSINESS, TECH&SCIENCE, ...) should have a heading tag (hx)
- In the NEWSLETTER section the input type should be email
- The NEWSLETTER section disappears in tablet and mobile views on your page, but it shouldn't
-  Try to limit as much as possible your sass styling as the purpose of this project is to apply bootstrap as much as possible  

### Happy Coding :computer: :computer_mouse: 

If you have any queries, don't hesitate to contact me via:
[LinkedIn](https://www.linkedin.com/in/henok-mekonnen-2a251613/) | [Twitter](https://twitter.com/henatan99) | Henok Mekonnen on Slack

**Review by Temmarie — CHANGES_REQUESTED** [review]
## Changes Required! :recycle:

### Hi @srizzuto and @vikitaotiz    ! :wave: :wave:

#### You have done well so far, I had to take a second look cause your project looks almost exactly like the actual site!  :clap: However, there are changes required for you to make in order for this project to be approved. Note that you have 1 review left according to the  [Code Reviews Limit Policy](https://microverse.zendesk.com/hc/en-us/restricted?return_to=https%3A%2F%2Fmicroverse.zendesk.com%2Fhc%2Fen-us%2Farticles%2F1500004088561).
- - -

### **Recommended**

**Section Specific requirements**
- [x] **You are missing certain parts of your project which includes:**
- In The Magazine,
- The Editor's Pick
- Newspaper main sections,
- Subscribe.

It seems that while you were making the previously required changes, you broke something in your code. 

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Comment by srizzuto** [comment]
Changes made as required!

**Review by DeliceLydia — APPROVED** [review]
# Status; Approved image image

Congratulations @srizzuto and @vikitaotiz for making all changes requested by previous TSEs your page is looking exactly like the original this required courage and hard work good job guys! 

- Page is looking good on all devices
- README is descriptive
- PR is meaningful

## Kudos once again feel free to merge and move on to the next project

All the best,

Lydia Ingabire

**Pull request merged**
