### PR TITLE
First milestone: Using Bootstrap

### PR DESCRIPTION
**Pull request by srizzuto**
This is the first Milestone of the Using Bootstrap collaborative project.

The goal of the project it's to apply Bootstrap technology on our website while being responsive.

SASS it's also included.

### CODE REVIEW

**Review by DeliceLydia — CHANGES_REQUESTED** [review]
# Status: Change Requested

Amazing job so far @srizzuto and @vikitaotiz your project is almost done
## To Highlights image

- Codes looks clean and easy to read

### Header

- The Newsweek logo has a link
- Logo In desktop it is centered
- In tablet and mobile, it is aligned to the left
- Contains a date in the same format on the source page (only on the desktop)
- Login and Subscribe have links
-  In mobile, the Login button changes into an icon

### The main navigation (menu)
- Uses a nav tag
- Each option has a link
- It has a form with the search field
- In mobile and table, the menu hides, and show a hamburger button
- The size of the elements change in desktop, tablet, and mobile

### Footer
- The social media icons have links
- The main navigation items have links
- The content-disposition changes to the correct place in desktop, tablet, and mobile

## To Improve image

- Logos for header and footer has to be links
- Remember to add in your README How to run the project locally to make it more professional

## Work on that and submit another CRR and remember that you still have only 2 code reviews and work accordingly

# Happy Coding image

Lydia Ingabire

**Comment by srizzuto** [comment]
Changes made as required!

**Review by Dipeshtwis — CHANGES_REQUESTED** [review]
# Status: ♻️ Changes Required ♻️
## Hi @srizzuto and @vikitaotiz, I'm Dipesh your reviewer for this PR.

Your clone is awesome. It looks like the exact one. Good to see that you have fixed almost all the changes told in the previous review. 👏 👏

But in order to approve we have to work on some of the changes mentioned below which are also mentioned above.

## For Approval

- [x] It has a form with the search field instead of anchor tag.

Screenshot (1289)_LI

- [x] It should cover all the space you can achieve by increasing the font or by giving some margin.

Screenshot (1288)_LI

- [ ] In the tablet view It should be right-aligned (marked with dark green) and instead of avatar it would be **LOGIN** button (marked with light green). Remember what the previous TSE says. Only in mobile, the Login button changes into an icon.

newsweek

Fix this and Request another code review.

## Reminder

**"As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) now, you have only 1 code review left for this project. If you think that the code review was not fair, you can [request a second-opinion using this form](https://airtable.com/shrQAqnBwek5a0O0s). "**

Code review by **Dipesh Kumar**

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
Happy Coding
[Dipesh Kumar](https://deeptwist.tk)
[Twitter](https://twitter.com/97deepeshkumar)

**Comment by srizzuto** [comment]
All changes made as required!

**Review by Dipeshtwis — APPROVED** [review]
# Status: Approved ✔️

## Hi @srizzuto and @vikitaotiz.

Good job on implementing the suggested changes.

**You may close this Pull Request and merge the changes.**

## Nice to have 
- It will look good when the search icon aligned with the search input. you can achieve this by a `margin` or `position` property.
  
**Keep being awesome devs and good luck with your next milestone!**
---------

Cheers and Happy coding!👏👏👏

(Feel free to contact me on slack by the handle of  **deep** if you have any additional questions).
[Dipesh Kumar](https://deeptwist.tk) | [Twitter](https://twitter.com/97deepeshkumar)

**Pull request merged**
